# Generated by Django 4.2.17 on 2025-07-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_imageupload_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('production_year', models.PositiveIntegerField()),
                ('insurance_status', models.CharField(max_length=100)),
                ('usage_years', models.PositiveIntegerField()),
                ('major_accident', models.BooleanField()),
                ('image', models.ImageField(upload_to='used_cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
